### ISSUE TITLE
Search for kanji by drawing/handwriting

### ISSUE THREAD

**Issue by maxigaz** [obfusk/jiten#128]
First of all, thank you for your work! I’ve been using jiten through the web interface of your hosted instance as well as locally through the F-Droid package, and I like it a lot so far.

Do you have any plans to add the ability to recognise kanji through handwriting (with the mouse or touchscreen), similar to the [input option](https://jisho.org/#handwriting) found on Jisho.org?

**Comment by obfusk** [comment]
Thanks! I'm glad you like it :smile_cat:

I did consider adding something like that, but sadly OCR doesn't work and I couldn't find any existing Python libraries for handwriting recognition.

I'm currently using [Kanji draw](https://f-droid.org/en/packages/ch.seto.kanjirecog) to draw kanji on Android (and [Mozc for Android](https://f-droid.org/packages/org.mozc.android.inputmethod.japanese) to write Japanese directly), which covers my own handwriting needs.

But I'll put it on my TODO list and I'll definitely consider implementing it if it's not too much work :)

**Comment by maxigaz** [comment]
I’ve just tried Kanji draw for the first time and it looks quite useful. Thank you for the suggestion!

I’ve been looking for similar applications for Linux (preferably FOSS), and none of which I’ve found are maintained anymore. So, new solutions would be very welcome (at least until my kanji skills become better).

**Comment by obfusk** [comment]
@maxigaz if you feel like beta-testing: https://github.com/obfusk/kanjidraw :)

I'll work on integrating it into jiten when I have more time.

**Comment by maxigaz** [comment]
Very nice! Thank you!

It's working fine so far. I'll let you know if I find any bugs.

**Comment by obfusk** [comment]
> I'll work on integrating it into jiten when I have more time.

It seems to be working well enough... so it's now live on https://jiten.obfusk.dev :)

> It's working fine so far. I'll let you know if I find any bugs.

:+1:

**Comment by maxigaz** [comment]
> It seems to be working well enough... so it's now live on https://jiten.obfusk.dev :)

> if you want to beta-test the android app, you can manually install a newer version from my custom f-droid repo.

Very good! Thank you very much!

**Comment by obfusk** [comment]
I just added a "fuzzy" search option and a "+/- 1 stroke" option.

**Comment by maxigaz** [comment]
Excellent idea!

I've just tried these options with the character 水(みず), intentionally drawing it in three strokes instead of four (drawing the two lines on the right as a single stroke). It didn't show up in the search results at all. (On the other hand, if I draw it correctly in four strokes, it shows up as the first result.)

**Comment by obfusk** [comment]
My versions of "fuzzy" and "+/- 1" are different from the ones used by the kanji draw app. I think mine should be faster, but I'm not sure which is more accurate.

I'm currently showing a maximum of 25 results; in my experience, if that's not enough I'm better off searching by radicals or SKIP code instead of looking through tons of matches.

I've tested w/ 猫:
- wrong stroke order/direction w/ "fuzzy" works
- skipping one stroke w/ "+/- 1" works
- combining both doesn't work (too many "better" matches I assume)

I've now also tested w/ 水:
- wrong stroke order/direction w/ "fuzzy" works
- skipping one stroke w/ "+/- 1" works
- combining both also works

So I'm not sure why it's not working for you :sweat_smile:

**Comment by maxigaz** [comment]
I've just tried again, and I got better results this time. (Although in one case it still doesn't have any matches.)

Here's the drawing itself:
![jiten-kanjidraw-1](https://user-images.githubusercontent.com/10419911/118185020-58748200-b43c-11eb-843b-38e2251892c9.png)

Results with "fuzzy" enabled: no matches
![jiten-kanjidraw-2](https://user-images.githubusercontent.com/10419911/118185159-8063e580-b43c-11eb-92b5-55ca115c73a9.png)

Results with "+/- 1" enabled: match on the first line
![jiten-kanjidraw-3](https://user-images.githubusercontent.com/10419911/118185198-8f4a9800-b43c-11eb-9259-c68efa887211.png)

Results with both enabled: match on the third line
![jiten-kanjidraw-4](https://user-images.githubusercontent.com/10419911/118185268-a12c3b00-b43c-11eb-88a4-ebd1f3a6c22c.png)

**Comment by obfusk** [comment]
> Results with "fuzzy" enabled: no matches

Fuzzy still requires the same *number* of strokes.

**Comment by obfusk** [comment]
Do you get better results if you leave less "empty" space around the drawing?

**Comment by obfusk** [comment]
> Do you get better results if you leave less "empty" space around the drawing?

This ugly drawing gets me 水 as the first result.

![Screenshot_2021-05-13 jiten - kanji](https://user-images.githubusercontent.com/1260687/118189215-ca9b9580-b441-11eb-9ac3-9e788eda48ab.png)

**Comment by maxigaz** [comment]
> Fuzzy still requires the same *number* of strokes.

Oh, I see! I wasn't sure how it worked, so I figured it might still pick it up somehow.

> Do you get better results if you leave less "empty" space around the drawing?

Do you mean if the drawing is bigger and closer to the edges of the drawing area? In that case, 水 appears two lines further down.

**Comment by maxigaz** [comment]
> > Do you get better results if you leave less "empty" space around the drawing?
> 
> This ugly drawing gets me 水 as the first result.
> 
> ![Screenshot_2021-05-13 jiten - kanji](https://user-images.githubusercontent.com/1260687/118189215-ca9b9580-b441-11eb-9ac3-9e788eda48ab.png)

Each time I draw it I get different results with these options. One time with "+/- 1 stroke", it appeared as the first match as well, although I can't reproduce it.

But now I understand that "fuzzy" is not enough in this case, and with the other combinations, it does show up among the results. I guess that's what counts. :)

**Comment by obfusk** [comment]
> Do you mean if the drawing is bigger and closer to the edges of the drawing area?

The algorithm looks at the position of (the beginning and ending of) the strokes within the square (divided into a 3x3 grid) and matches them against the reference kanji. So if you draw the kanji "too small", it won't match.

**Comment by obfusk** [comment]
Thanks for the feedback! It's hard to know what to do to make things easy to understand for first-time users when you already know how everything works. I'll see what I can do to make it easier.

**Comment by obfusk** [comment]
"ignore stroke order & direction" is more accurate, but also a lot more text than "fuzzy" :)

**Comment by obfusk** [comment]
> But now I understand that "fuzzy" is not enough in this case.

I was hoping that the fact that "+/- 1 stroke" is a separate option would suggest that "fuzzy" doesn't *also* do that.

**Comment by obfusk** [comment]
> I was hoping that the fact that "+/- 1 stroke" is a separate option would suggest that "fuzzy" doesn't _also_ do that.

That and the fact that all the results for the "3-stroke 水" have 3 strokes :)

**Comment by maxigaz** [comment]
> > I was hoping that the fact that "+/- 1 stroke" is a separate option would suggest that "fuzzy" doesn't _also_ do that.
> 
> That and the fact that all the results for the "3-stroke 水" have 3 strokes :)

Yes, it makes sense, I agree with that. Again, I had no idea how it worked. I thought, maybe it "looks" similar, so that would be a match, regardless of the number of strokes? Apparently, I was wrong. That's all I can say about it now.

**Comment by obfusk** [comment]
> Apparently, I was wrong.

Which is my fault for not providing more information about how it works, thus allowing you to provide useful feedback on how intuitive it is for someone who didn't built it :)

**Comment by obfusk** [comment]
* I renamed "fuzzy" to "ignore stroke order & direction".
* I added some help text.
* I added a grid to the drawing area.

**Comment by maxigaz** [comment]
> I added a grid to the drawing area.

While I don't particularly mind it, I would personally welcome an option to turn it off.

**Comment by obfusk** [comment]
> While I don't particularly mind it, I would personally welcome an option to turn it off.

I can do that if you really want it. But I added it because it helps (me and another tester) to draw more accurately (i.e. drawing the strokes in the "correct" part(s) of the grid) and get better results with less effort.

**Comment by obfusk** [comment]
> While I don't particularly mind it, I would personally welcome an option to turn it off.

Done.

**Comment by maxigaz** [comment]
Thank you very much!

**Comment by obfusk** [comment]
@maxigaz it seems to be working reasonably well, so I'm closing this for now; but feel free to provide more feedback/requests :)
