### ISSUE TITLE
fix dark theme input fields

### ISSUE THREAD

**Issue by obfusk** [obfusk/jiten#130]
See #129.

**Comment by obfusk** [comment]
@maxigaz I'm finally working on this. You can test it at https://jiten-py-staging.herokuapp.com. I'd appreciate any feedback.

**Comment by maxigaz** [comment]
Well, I don't want to be too nitpicky about the colour choices, so I'll just say that I like that the fields now don't look out of place anymore.

Thank you!

**Comment by obfusk** [comment]
The changes are now live on https://jiten.obfusk.dev. A new release of the offline android app may take a while.
