### ISSUE TITLE
Ability to adjust font size

### ISSUE THREAD

**Issue by maxigaz** [obfusk/jiten#131]
Having an option to adjust the font size (especially for Japanese characters) would be great.

**Comment by obfusk** [comment]
Could you be more specific as to what you're trying to achieve?

Because you can already:
* use the standard zoom options of desktop browsers
* use pinch zoom on Android
* change system-wide font sizes on Android

**Comment by maxigaz** [comment]
I meant increasing the size of Japanese and Latin characters individually. (For example, the ability to set the former to `1.28rem` and the latter to `1.1rem`.)

> use the standard zoom options of desktop browsers

I've tried that already, but then when I increase the zoom size so that the Kanji characters are comfortable to read, the rest of the webpage seem too big. Also, is it possible to make the browser (Firefox in my case) remember this option only for Jiten, without using any addons?

**Comment by obfusk** [comment]
@maxigaz I'm finally working on this. You can test it at https://jiten-py-staging.herokuapp.com. I'd appreciate any feedback.

**Comment by obfusk** [comment]
> Also, is it possible to make the browser (Firefox in my case) remember this option only for Jiten, without using any addons?

I thought Firefox automatically remembers the zoom setting per website?

**Comment by obfusk** [comment]
> @maxigaz I'm finally working on this. You can test it at https://jiten-py-staging.herokuapp.com. I'd appreciate any feedback.

I added a new "large japanese font" setting (on the `styling` branch).

**Comment by maxigaz** [comment]
> I thought Firefox automatically remembers the zoom setting per website?

No, at least not for me. For example, if I set the zoom to 120%, close the tab containing the web page, and open it again from the History. It's reset to 100%.

> I'm finally working on this. You can test it at https://jiten-py-staging.herokuapp.com. I'd appreciate any feedback.

It's definitely better IMO, although the size of the radicals and variants listed among the search results don't seem to change at all. (For reference, I'm looking at [this page](https://jiten-py-staging.herokuapp.com/kanji?query=%E7%8C%AB) right now.)

In my customized CSS, I also increased the size of the search input field, to make it look similar to that of Jisho.org. So, this is another thing that could be added if you're comfortable with it.

Thank you for your work!

**Comment by obfusk** [comment]
> No, at least not for me. For example, if I set the zoom to 120%, close the tab containing the web page, and open it again from the History. It's reset to 100%.

Doing exactly that does work for me.

**Comment by obfusk** [comment]
> the size of the radicals and variants listed among the search results don't seem to change at all.

Correct. Unfortunately, I can't just resize everything at once because I have to take the current relative sizes into account. So I started with the "most important stuff", and was hoping for some feedback on what else I should adjust :)

If you'd like the size difference to be smaller or larger, let me know.

**Comment by obfusk** [comment]
I've increased the font size of some more elements. Let me know if that works for you :)

**Comment by obfusk** [comment]
> > No, at least not for me. For example, if I set the zoom to 120%, close the tab containing the web page, and open it again from the History. It's reset to 100%.
> 
> Doing exactly that does work for me.

You may want to check if `browser.zoom.siteSpecific` is set to `true` in `about:config`.

**Comment by maxigaz** [comment]
> I've increased the font size of some more elements. Let me know if that works for you :)

I can see the search field is bigger now. I like it, thank you!

> You may want to check if `browser.zoom.siteSpecific` is set to `true` in `about:config`.

You're right! I'm not sure why I had this set to `false`. (My Firefox profile is several years old, so it could have been an addon I tried out for a short time.) Thank you for the tip!

**Comment by obfusk** [comment]
The changes are now live on https://jiten.obfusk.dev. A new release of the offline android app may take a while.
