### ISSUE TITLE
Include search query in webpage title

### ISSUE THREAD

**Issue by maxigaz** [obfusk/jiten#135]
It would be great if the search query was added to the page title when the web interface is used.

For example, if I search for "use", the title of the page showing the results for this word could change to "use - jiten - jmdict".

This would make navigation in the browsing history much easier. (Currently, by looking at the history popup list, it's hard to tell which page contains the results for what exactly.)

![jiten-browser-history](https://user-images.githubusercontent.com/10419911/120455643-3ca63100-c395-11eb-8708-ea6cbd927d2c.png)

**Comment by maxigaz** [comment]
Thank you very much! It looks great on https://jiten.obfusk.dev.

**Comment by obfusk** [comment]
You're welcome :)

(I meant to add this at some point when it actually bothered me... which didn't happen yet, so I forgot about it :sweat_smile:)
