### ISSUE TITLE
web: lookup by rōmaji

### ISSUE THREAD

**Issue by pavlukivan** [obfusk/jiten#140]
on android, i usually have the english keyboard active, and it's a bit annoying to switch the layout every time i want to look a word up

**Comment by obfusk** [comment]
That's what the `あ` button to the left of the input field is for :)

**Comment by pavlukivan** [comment]
ah, i see... couldn't it be automated though, or is that too hard?

**Comment by obfusk** [comment]
> ah, i see... couldn't it be automated though, or is that too hard?

I'd have to guess whether you intended to search for roumaji or e.g. an English word, which I'd rather not even try :)

**Comment by pavlukivan** [comment]
i see, i'll just close this then, thanks for the info
