### ISSUE TITLE
Jiten Offline stops working permanently after running fine for a while

### ISSUE THREAD

**Issue by FrostKiwi** [obfusk/jiten#141]
Huge fan of Jiten. It's the only real good offline dict for android. Especially regarding listing pitch accent.

The offline version of the App stopped working on my OnePlus One with LineageOS 18.1. Worked fine for months, then upon opening the App, the loading animation never stops. Online version of the app was fine. Reinstalled Android 3 days ago. Jiten Offline ran fine for 2 days, then today same deal: stuck on an endless loading animation. Online Version is fine.
![Screenshot_20220420-174437_Jiten](https://user-images.githubusercontent.com/60887273/164190411-78335d1e-dffd-4af1-995d-3d6cd5d39541.png)

I installed Jiten Version 1.1.0 from F-Droid. Just to be sure, uninstalled and installed from the Google PlayStore. Same deal. Stuck.
One interesting symptom is a short lag in the loading animation 5 seconds after starting the app.
Based on my understanding, here is what Jiten Offline does: Starts a Jiten server on the phone and localhost connects to it. I suspect that small lag after 5 secs is the Server successfully starting the server, but failing to connect to it.

What can I provide to help with diagnosing this? I can create a logcat dump for instance...

PS: I carry a second phone just in case I need a quick vocab checked :S

**Comment by obfusk** [comment]
You mentioned LineageOS. You didn't happen to disable network access for the app? It doesn't need internet access, so you can disable wifi/data etc., but it does need the general network permission to connect to localhost.

I can't really work on Jiten atm. But feel free to send a logcat dump, I'll try to look at it when I can.

You could also try [running Jiten via Termux](https://github.com/obfusk/jiten#web-interface-on-android) and using the offline app or a browser to connect to localhost.

**Comment by obfusk** [comment]
It seems on Android 12, Jiten requires wifi/data permission as well (it still doesn't access the internet but it needs to run the server on localhost).

Closing this for now. Please reopen if your problem turns out to be unrelated to this.
