### ISSUE TITLE
Installation fails while building jiten._sqlite3_pcre on postmarketOS

### ISSUE THREAD

**Issue by maxigaz** [obfusk/jiten#156]
Hi!

I recently started using postmarketOS on a Moto G (osprey). I tried installing Jiten through `pipx install jiten`, and the installation failed with an error that pointed to the logs created by `pipx`. You can see the full log attached here: [cmd_2023-09-19_21.16.34_pip_errors.log.txt](https://github.com/obfusk/jiten/files/12670051/cmd_2023-09-19_21.16.34_pip_errors.log.txt)

The relevant part is this:

```
      running build_ext
      building 'jiten._sqlite3_pcre' extension
      creating build/temp.linux-aarch64-cpython-311
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/maxigaz/.local/pipx/venvs/jiten/include -I/usr/include/python3.11 -c sqlite3-pcre.c -o build/temp.linux-aarch64-cpython-311/sqlite3-pcre.o
      sqlite3-pcre.c:13:10: fatal error: pcre.h: No such file or directory
         13 | #include <pcre.h>
            |          ^~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jiten
ERROR: Could not build wheels for jiten, which is required to install pyproject.toml-based projects
```

I also tried cloning the repository with `git` and then running `make`, but I received the same error about `pcre.h` missing. Here's the full output of that command: [jiten-make-log.txt](https://github.com/obfusk/jiten/files/12670033/jiten-make-log.txt)

I'm quite new to postmarketOS, but my understanding is that, since it's based on Alpine Linux, it also uses musl-libc instead of glibc. Could this be related to the issue?

**Comment by obfusk** [comment]
I'm not familiar with the specifics of postmarketOS, but on Alpine Linux you would need to install the `pcre-dev` and `sqlite-dev` packages AFAIK.

**Comment by maxigaz** [comment]
> I'm not familiar with the specifics of postmarketOS, but on Alpine Linux you would need to install the `pcre-dev` and `sqlite-dev` packages AFAIK.

I can confirm, those two are also needed on postmarketOS. Thank you very much for the suggestion!
